//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exon.Recab.Service.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EmailTemplate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmailTemplate() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exon.Recab.Service.Resource.EmailTemplate", typeof(EmailTemplate).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!doctype html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;&lt;/head&gt;
        ///
        ///&lt;body dir=&quot;rtl&quot;&gt;
        ///    &lt;div class=&quot;header&quot; style=&quot;max-width:500px; margin:0 auto; height:50px; font-family:&apos;B Yekan&apos;,Tahoma,Arial;&quot;&gt;
        ///        &lt;img src=&quot;https://i.imgsafe.org/1dba4bc.png&quot; height=&quot;50&quot; style=&quot;float:right; display:inline-block;&quot; /&gt;
        ///        &lt;img src=&quot;https://i.imgsafe.org/be7e949.png&quot;  height=&quot;50&quot; style=&quot;float:left; display:inline-block;&quot;/&gt;
        ///    &lt;/div&gt;
        ///    &lt;div class=&quot;container&quot; style=&quot;color:rgba(0,0,0,.8); max-width:500px; background-color:#fafafa; bor [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AdvertiseConfirm {
            get {
                return ResourceManager.GetString("AdvertiseConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!doctype html&gt;
        ///&lt;html&gt;&lt;head&gt;&lt;/head&gt;
        ///&lt;body dir=&quot;rtl&quot;&gt;
        ///    &lt;div class=&quot;header&quot; style=&quot;max-width:500px; margin:0 auto; height:50px; font-family:&apos;B Yekan&apos;,Tahoma,Arial;&quot;&gt;
        ///        &lt;img src=&quot;https://i.imgsafe.org/1dba4bc.png&quot; height=&quot;50&quot; style=&quot;float:right; display:inline-block;&quot; /&gt;
        ///        &lt;img src=&quot;https://i.imgsafe.org/be7e949.png&quot; height=&quot;50&quot; style=&quot;float:left; display:inline-block;&quot; /&gt;
        ///    &lt;/div&gt;
        ///    &lt;div class=&quot;container&quot; style=&quot;color:rgba(0,0,0,.8); max-width:500px; background-color:#fafafa; border: [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AdvertiseSave {
            get {
                return ResourceManager.GetString("AdvertiseSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!doctype html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;&lt;/head&gt;
        ///&lt;body dir=&quot;rtl&quot;&gt;
        ///    &lt;div class=&quot;header&quot; style=&quot;max-width:500px; margin:0 auto; height:50px; font-family:&apos;B Yekan&apos;,Tahoma,Arial;&quot;&gt;
        ///        &lt;img src=&quot;https://i.imgsafe.org/1dba4bc.png&quot; height=&quot;50&quot; style=&quot;float:right; display:inline-block;&quot; /&gt;
        ///        &lt;img src=&quot;https://i.imgsafe.org/be7e949.png&quot; height=&quot;50&quot; style=&quot;float:left; display:inline-block;&quot; /&gt;
        ///    &lt;/div&gt;
        ///    &lt;div class=&quot;container&quot; style=&quot;color:rgba(0,0,0,.8); max-width:500px; background-color:#fafafa; borde [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AlertEmail {
            get {
                return ResourceManager.GetString("AlertEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!doctype html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///&lt;meta charset=&quot;UTF-8&quot;&gt;
        ///&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot;&gt;
        ///&lt;title&gt;تغییر کلمه عبور&lt;/title&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body dir=&quot;rtl&quot;&gt;
        ///    &lt;div class=&quot;header&quot; style=&quot;max-width:500px; margin:0 auto; height:50px; font-family:&apos;B Yekan&apos;,Tahoma,Arial;&quot;&gt;
        ///        &lt;img src=&quot;images/Rekab.png&quot; height=&quot;50&quot; style=&quot;float:right; display:inline-block;&quot; /&gt;
        ///        &lt;img src=&quot;images/farsi.png&quot;  height=&quot;50&quot; style=&quot;float:left; display:inline-block;&quot;/&gt;
        ///    &lt;/div&gt;
        ///    &lt;div class=&quot;conta [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ChangePasswordEmailTemplate {
            get {
                return ResourceManager.GetString("ChangePasswordEmailTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!doctype html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;&lt;/head&gt;
        ///&lt;body dir=&quot;rtl&quot;&gt;
        ///    &lt;div class=&quot;header&quot; style=&quot;max-width:500px; margin:0 auto; height:50px; font-family:&apos;B Yekan&apos;,Tahoma,Arial;&quot;&gt;
        ///        &lt;img src=&quot;https://i.imgsafe.org/1dba4bc.png&quot; height=&quot;50&quot; style=&quot;float:right; display:inline-block;&quot; /&gt;
        ///        &lt;img src=&quot;https://i.imgsafe.org/be7e949.png&quot; height=&quot;50&quot; style=&quot;float:left; display:inline-block;&quot; /&gt;
        ///    &lt;/div&gt;
        ///    &lt;div class=&quot;container&quot; style=&quot;color:rgba(0,0,0,.8); max-width:500px; background-color:#fafafa; border:1px [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DealershipConfirm {
            get {
                return ResourceManager.GetString("DealershipConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!doctype html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;&lt;/head&gt;
        ///
        ///&lt;body dir=&quot;rtl&quot;&gt;
        ///    &lt;div class=&quot;header&quot; style=&quot;max-width:500px; margin:0 auto; height:50px; font-family:&apos;B Yekan&apos;,Tahoma,Arial;&quot;&gt;
        ///        &lt;img src=&quot;https://i.imgsafe.org/1dba4bc.png&quot; height=&quot;50&quot; style=&quot;float:right; display:inline-block;&quot; /&gt;
        ///        &lt;img src=&quot;https://i.imgsafe.org/be7e949.png&quot; height=&quot;50&quot; style=&quot;float:left; display:inline-block;&quot; /&gt;
        ///    &lt;/div&gt;
        ///    &lt;div class=&quot;container&quot; style=&quot;color:rgba(0,0,0,.8); max-width:500px; background-color:#fafafa; bor [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PurchaseDetail {
            get {
                return ResourceManager.GetString("PurchaseDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!doctype html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;&lt;/head&gt;
        ///&lt;body dir=&quot;rtl&quot;&gt;
        ///    &lt;div class=&quot;header&quot; style=&quot;max-width:500px; margin:0 auto; height:50px; font-family:&apos;B Yekan&apos;,Tahoma,Arial;&quot;&gt;
        ///        &lt;img src=&quot;https://i.imgsafe.org/1dba4bc.png&quot; height=&quot;50&quot; style=&quot;float:right; display:inline-block;&quot; /&gt;
        ///        &lt;img src=&quot;https://i.imgsafe.org/be7e949.png&quot; height=&quot;50&quot; style=&quot;float:left; display:inline-block;&quot; /&gt;
        ///    &lt;/div&gt;
        ///    &lt;div class=&quot;container&quot; style=&quot;color:rgba(0,0,0,.8); max-width:500px; background-color:#fafafa; border:1px [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SendVerficationCode {
            get {
                return ResourceManager.GetString("SendVerficationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!doctype html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///&lt;/head&gt;
        ///&lt;body dir=&quot;rtl&quot;&gt;
        ///    &lt;div class=&quot;header&quot; style=&quot;max-width:500px; margin:0 auto; height:50px; font-family:&apos;B Yekan&apos;,Tahoma,Arial;&quot;&gt;
        ///        &lt;img src=&quot;https://i.imgsafe.org/1dba4bc.png&quot; height=&quot;50&quot; style=&quot;float:right; display:inline-block;&quot; /&gt;
        ///        &lt;img src=&quot;https://i.imgsafe.org/be7e949.png&quot; height=&quot;50&quot; style=&quot;float:left; display:inline-block;&quot; /&gt;
        ///    &lt;/div&gt;
        ///    &lt;div class=&quot;container&quot; style=&quot;color:rgba(0,0,0,.8); max-width:500px; background-color:#fafafa; bor [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Wellcome {
            get {
                return ResourceManager.GetString("Wellcome", resourceCulture);
            }
        }
    }
}
