
namespace Exon.Recab.Domain.Constant.CS.Exception
{
    public enum ExceptionType
    {
        // system error
        InternalError = 2000,
        BadRequest = 2001,        

        //api call Error
        ServiceUnavailable = 3000,

        //Model State
        ModelStateInvalid = 4000 ,
        Required = 4001,
        MinLength =4002,
        ComparePassword = 4003,
        Email =4004,
        Numeric =4005,
        MaxLength = 4006,
        CategoryFeatureModelStateError = 4007,
        FeatureValueModelStateErrorWrongId = 4008,
        CategoryFeatureModelStateErrorWrongMulti =4009,
        CategoryFeatureModelStateErrorNullId = 4010,
        FeatureValueModelStateErrorRegex = 4011,

        //Business

        //User
        RedundantMobileNumber = 6000,
        WrongUserNameORPassword = 6001,
        UserNotFound = 6002,
        MobileCodeInValid = 6003,
        UserPackageCreditNotFound = 6004,
        UserAlreadyExist = 6005,

        //ADS
        ProductNotFound = 6100,
        FavouriteProductExist = 6101,

        //public
        CityNotFound = 6200,
        CategoryNotFound = 6201,
        FeatureValueInvalid = 6202,
        CategoryFeatureInvalid = 6203,
        ReviewNotFound = 6204,
        BadRateData = 6205,
        TodayPriceNotFound = 6206,
        FavouriteNotFound = 6207,
        FeedBackExist = 6208,
        ArticleNotFound = 6209,
        DealershipNotFound = 6210,
        ParentCategoryNotFound = 6211,
        ExchangeCategoryAlreadyExist = 6212,
        AndroidElementNotFound = 6213,
        HtmlElementNotFound = 6214,
        RangCategoryFeatureNotFound = 6215,
        ExchangeCategoryNotFound = 6216,
        CategoryFeatureNotFound = 6217,
        CategoryFeatureNotAvalableInFeatureValueIcon = 6218,
        FeatureValueNotFound = 6219,
        CategoryFeatureNotAvalableInCategoryFeatureIcon = 6220,
        FeatureValueExist = 6221,
        FeatureValueNotExist = 6222,
        CategoryFeatureParentAlreadyExist = 6223,
        CategoryFeatureChildAlreadyExist = 6224,
        CategoryFeatureChildNotFound = 6225,
        CpptIdNotFound =6226,
        VoucherInvalid = 6227,
        PriceNotFoundForCpptId = 6228,
        PriceForCpptIdIncorrectFormat = 6229,
        VocherConfigNotFound = 6230,
        PictureCountInvalid = 6231,
        SomeCategoryFeatureRedundant = 6232,
        MissedInsertCategoryFeature = 6233,
        InvalidInsertCategoryFeature = 6234,
        UserNotExist = 6235,
        TodayPriceHistoryNotFound = 6236,
        UpdateCountLimit = 6237,
        DealershipCantAdd = 6238,
        DealershipCantRemove = 6239,
        PurchaseTypeNotFound = 6240,
        CategoryPurchaseTypeNotFound = 6241,
        CategoryPurchaseTypeHasUsedItem = 6242,
        CategoryPurchasePackageTypeNotFound = 6243,
        PurchaseTypeExistInCPT = 6244,
        AlertNotFound = 6245,
        PackageTypeNotFound = 6246,
        CategoryPurchasePackageTypeAlreadyExist = 6247,
        TodayPriceOptionNotFound = 6248,
        ArticleStructureNotFound = 6250,
        TodayPriceWrongFilter = 6251,
        FeatureValueParentNotFound = 6252,
        FeatureValueParentAlreadyExist = 6253,
        FeatureValueChildAlreadyExist = 6254,     
        RaiseQuotaLimit = 6256,       
        CategoryNotCompatible = 6258,
        ArticleStructureHasChild = 6259,
        ArticleStructureHasArticle = 6260,
        RoleNotFound = 6261,
        ResourceNotFound = 6262,
        ResourceParentNotFound = 6263,
        AccessDenied = 6264,
        RoleHasPermission = 6265,
        RoleHasUserRole = 6266,
        UserRoleNotFound = 6267,
        PermissionNotFound = 6268,
        ProductHasNoExchange = 6269,
        FeatureValueAlreadyExist = 6270,
        CategoryPurchasePackageTypeNotFoundMissdItemForConfig = 6271,
        CPPTExistInUserCredit = 6272,
        CreditNotEnough = 6273,
        CategoryPurchaseTypeAlreadyExist = 6274,
        SameParentAndChild = 6275,
        EnableCFAlreadyExist = 6276,
        RedundantUserNewsEmail = 6277,
        NewsNotFound = 6278,
        UserEmailNotActive = 6279,
    }
}
